### ISSUE TITLE
Suggestion: Add functionality to open links in tables in new tab / window

### ISSUE THREAD

**Issue by joecorkerton** [mode/alamode#13]
The behaviour of links in tables is currently a little awkward in that it opens in the same window. It would be much more intuitive if by default the links open in a new tab or window, or at least add this functionality through a new parameter. 

I believe to fix this all that is needed is a simple change line 116 in alamode.js to the following: `            cells.eq(columnToShow).html("<a href='" + encodeURI(url) + "' target='_blank'>" + cellContent + "</a>")`

**Comment by plentz** [comment]
@joecorkerton why did you closed the issue? have you found a way around it?
