### ISSUE TITLE
Links scrambled after scrolling

### ISSUE THREAD

**Issue by frankjwu** [mode/alamode#28]
I'm looking at [this example report](https://modeanalytics.com/modeanalytics/reports/6b8ab493c66c/runs/1355c87cd743), provided by the Mode documentation [here](https://community.modeanalytics.com/gallery/table-links/).

I made a [clone of this report](https://modeanalytics.com/frank_trialspark/reports/7e710a98c69c) and created a version of this report where the table must be scrolled. You'll notice that upon scrolling, the table links will no longer point to the correct locations.

**Comment by ninjudd** [comment]
I'm actually having this same issue on my reports even without scrolling 😞

I followed the instructions here exactly: https://community.modeanalytics.com/gallery/table-links/

We are the link for some rows showing up several times, while the link for other rows is never used.

**Comment by bstancil** [comment]
Hey @frankjwu and @ninjudd, this looks like it's being caused by an update to the table element in Mode. We'll look into getting it fixed!

**Comment by bstancil** [comment]
This should now be fixed!
