### ISSUE TITLE
addLinksToTables option to open in same window

### ISSUE THREAD

**Issue by bflannery** [mode/alamode#35]
My current application is running mod white-label embedded reports using `addLinksToTables` and would like to have the report links stay within the same window/tab so the user history is intact for navigation. 

I noticed @joecorkerton was having the opposite issue in [Issue-13](https://github.com/mode/alamode/issues/13).

At the time of writing this, the code does not allow and option to set the target on the links. Would it be possible to add this functionality?

**Comment by plentz** [comment]
@bflannery I think that this is the current (default) behavior and actually, @joelcarron's issue is the one that needs to be solved 🤔

**Comment by leqilong** [comment]
Hi @plentz @bflannery - yeah the current behavior is that the tabs always opened in the same tab. 
There's a recent PR that adds a parameter in the function call that would allow you to choose whether you want links to open in new tab or not. I've deployed that PR. And now you could use the parameter "open_in_new_tab" to control this. Example:
`<script>
  alamode.addLinksToTables({
    table_id: "table_12345",
    query_name: "q1",
    link_columns: ["url"],
    link_urls: ["{{url}}"],
    open_in_new_tab: true
  });
</script>`

**Comment by bflannery** [comment]
Thanks getting back to me @leqilong @plentz that recent PR fixed the issue I was having. When the link is clicked, a new window does not open unless the `open_in_new_tab` key is true

**Comment by plentz** [comment]
So we can close this one, right?

**Comment by leqilong** [comment]
Yup, @plentz. Closing this one now.
